
# This is a template Makefile generated by rpcgen

# Parameters

PROGRAM_NAME = file
CLIENT = $(PROGRAM_NAME)_client
SERVER = $(PROGRAM_NAME)_server


SOURCES_CLNT.cpp = $(PROGRAM_NAME)_client.cpp
SOURCES_CLNT.h = $(PROGRAM_NAME)_client.h
SOURCES_SVC.cpp = $(PROGRAM_NAME)_server.cpp
SOURCES_SVC.h = $(PROGRAM_NAME)_server.h
SOURCES.x = $(PROGRAM_NAME).x

TARGETS_SVC.c = $(PROGRAM_NAME)_svc.c $(PROGRAM_NAME)_xdr.c
TARGETS_CLNT.c = $(PROGRAM_NAME)_clnt.c $(PROGRAM_NAME)_xdr.c
TARGETS = $(PROGRAM_NAME).h $(PROGRAM_NAME)_xdr.c $(PROGRAM_NAME)_clnt.c $(PROGRAM_NAME)_svc.c

OBJECTS_CLNT = $(SOURCES_CLNT.cpp:%.cpp=%.o) $(TARGETS_CLNT.c:%.c=%.o)
OBJECTS_SVC = $(SOURCES_SVC.cpp:%.cpp=%.o) $(TARGETS_SVC.c:%.c=%.o)

# Compiler flags

CFLAGS += -g
LDLIBS += -lnsl
RPCGENFLAGS =

# Targets

all : $(CLIENT) $(SERVER)

$(TARGETS) : $(SOURCES.x)
	rpcgen $(RPCGENFLAGS) $(SOURCES.x)

$(OBJECTS_CLNT) : $(SOURCES_CLNT.cpp) $(SOURCES_CLNT.h) $(TARGETS_CLNT.c)

$(OBJECTS_SVC) : $(SOURCES_SVC.cpp) $(SOURCES_SVC.h) $(TARGETS_SVC.c)

$(CLIENT) : $(OBJECTS_CLNT)
	$(LINK.cpp) -o $(CLIENT) $(OBJECTS_CLNT) $(LDLIBS)

$(SERVER) : $(OBJECTS_SVC)
	$(LINK.cpp) -o $(SERVER) $(OBJECTS_SVC) $(LDLIBS)

 clean:
	 $(RM) $(TARGETS) $(OBJECTS_CLNT) $(OBJECTS_SVC) $(CLIENT) $(SERVER)

